name: Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/wft
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine toml
    - name: Extract version from pyproject.toml
      id: get_version
      run: |
        VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
    - name: Check if version exists on PyPI
      id: check_version
      run: |
        if pip install wft==${{ steps.get_version.outputs.VERSION }}; then
          echo "Version already exists on PyPI"
          echo "EXISTS=true" >> $GITHUB_OUTPUT
        else
          echo "Version does not exist on PyPI"
          echo "EXISTS=false" >> $GITHUB_OUTPUT
        fi
    - name: Build package
      if: steps.check_version.outputs.EXISTS == 'false'
      run: python -m build
    - name: Publish package distributions to PyPI
      if: steps.check_version.outputs.EXISTS == 'false'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
    - name: Create and push tag
      if: steps.check_version.outputs.EXISTS == 'false'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a v${{ steps.get_version.outputs.VERSION }} -m "Release v${{ steps.get_version.outputs.VERSION }}"
        git push origin v${{ steps.get_version.outputs.VERSION }}
    - name: Create GitHub Release
      if: steps.check_version.outputs.EXISTS == 'false'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.get_version.outputs.VERSION }}
        generate_release_notes: true
        files: |
          dist/*
